# Generated by Django 3.2.14 on 2022-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220728_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'ADMIN'), ('1', 'SELLER'), ('2', 'SUPPORT')], default='0', max_length=2),
        ),
    ]
