# Generated by Django 3.2.14 on 2022-08-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', ''), ('1', 'SELLER'), ('2', 'SUPPORT')], default='0', max_length=2),
        ),
    ]
