# Generated by Django 3.2.14 on 2022-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220803_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'GESTION'), ('1', 'SELLER'), ('2', 'SUPPORT')], max_length=2),
        ),
    ]
