# Generated by Django 3.2.14 on 2022-08-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', ''), ('1', 'SELLER'), ('2', 'SUPPORT'), ('3', 'GESTION')], max_length=1),
        ),
    ]
